# Lecture 2

In [1]:
# Auto-completion using tab
an = 1
an_example = 'gppd'

In [2]:
an_example

'gppd'

In [3]:
# Introspection
mylist=[1,2,3]

In [4]:
dir(mylist)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [5]:
# documentation
def addnum(a,b):
    """
    Add two number a and b
    """
    return a + b

In [6]:
addnum?

In [7]:
# File using numpy
a = [1, 2, 3]

In [9]:
import numpy as np
np.savetxt('a.txt',a)

In [12]:
b = np.loadtxt('a.txt')
b

array([ 1.,  2.,  3.])

In [13]:
# working directory
import os
os.getcwd()


'C:\\Users\\jpeng3'

In [14]:
os.chdir("D:\Dropbox\Teaching\Data Science using Python\OPIM5894\Lecture2")
os.getcwd()

'D:\\Dropbox\\Teaching\\Data Science using Python\\OPIM5894\\Lecture2'

In [15]:
# Relative path
np.savetxt('a.txt',a)

In [16]:
np.savetxt('../a.txt',a)

In [17]:
np.savetxt('sub/a.txt',a)

# Matrix Algebra

In [18]:
# vector
import numpy as np
a  = np.array([1,2,3])

In [19]:
a

array([1, 2, 3])

In [20]:
a.shape

(3,)

In [21]:
a.shape=(3,1)
a

array([[1],
       [2],
       [3]])

In [22]:
a.shape=(1,3)
a

array([[1, 2, 3]])

In [25]:
m = np.random.randint(1,10, size=(3,3))
m

array([[5, 9, 4],
       [9, 4, 3],
       [3, 9, 1]])

In [27]:
# Transpose
m.transpose()

array([[5, 9, 3],
       [9, 4, 9],
       [4, 3, 1]])

In [28]:
m.T

array([[5, 9, 3],
       [9, 4, 9],
       [4, 3, 1]])

In [32]:
m = np.random.randn(3,3)
m
(m + m.T)/2


array([[ 0.27079337,  0.45617054, -1.25189586],
       [ 0.45617054,  1.57247103, -0.53130613],
       [-1.25189586, -0.53130613,  0.48883539]])

In [35]:
# Matrix multiplication
a=np.random.randn(2,3)
b=np.random.randn(3,2)

In [36]:
a

array([[-1.75434076, -0.04333512, -0.44436643],
       [ 0.00185393, -0.84809008, -0.21900085]])

In [37]:
b

array([[-0.01752716,  1.71033642],
       [-1.57866465, -1.02694961],
       [ 1.97355631,  0.07292677]])

In [39]:
# Matrix multiplication
np.dot(b, np.dot(a,b))

array([[ 1.5642357 ,  1.5200961 ],
       [ 0.29688046,  3.83643461],
       [-1.46895948, -5.83522571]])

In [41]:
np.dot(np.dot(b,a),b)


array([[ 1.5642357 ,  1.5200961 ],
       [ 0.29688046,  3.83643461],
       [-1.46895948, -5.83522571]])

In [42]:
a = np.array([1,2,3])

In [44]:
np.dot(a, a.T)

14

In [45]:
np.dot(a.T, a)

14

In [46]:
a.shape=(3,1)

In [47]:
a

array([[1],
       [2],
       [3]])

In [48]:
# Inner product
np.dot(a.T, a)

array([[14]])

In [49]:
# Outer product
np.dot(a, a.T)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [50]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [51]:
# Elementwise Multiplication
x

array([[1, 2],
       [3, 4]])

In [52]:
y

array([[5, 6],
       [7, 8]])

In [53]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [54]:
x*y

array([[ 5, 12],
       [21, 32]])

In [56]:
# Determinant
np.linalg.det(y)

-1.9999999999999989

In [57]:
# Rank
np.linalg.matrix_rank(x)


2

In [59]:
x = np.array([[1.5, 2],[3,4]])

In [61]:
np.linalg.matrix_rank(x)

1

In [62]:
y

array([[5, 6],
       [7, 8]])

In [63]:
# inverse
np.linalg.inv(y)

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [64]:
np.dot(np.linalg.inv(y), y)

array([[  1.00000000e+00,   0.00000000e+00],
       [ -3.55271368e-15,   1.00000000e+00]])

In [65]:
# Condition number
# well-conditioned
m = np.array([[1,0,-1],[0,1,0],[1,0,1]])

In [66]:
m

array([[ 1,  0, -1],
       [ 0,  1,  0],
       [ 1,  0,  1]])

In [67]:
np.linalg.cond(m)

1.4142135623730951

In [68]:
# ill-conditioned
m2 = np.array([[1,0,0.9],[0,1,0],[1,0,1]])

In [69]:
np.linalg.cond(m2)

38.073735174775663

In [70]:
# Condition number calculation by SVD
u,s,v=np.linalg.svd(m2)

In [71]:
s

array([ 1.95124922,  1.        ,  0.05124922])

In [72]:
# largest singular values divided by smallest
s[0]/s[2]

38.073735174775663